// Maps each entry in src/constants/countries.ts to its common currency symbol/shorthand. Several
// countries share a symbol (e.g. the Eurozone, or many unrelated "$"-denominated currencies) —
// that's expected and matches everyday display conventions, not a claim that e.g. AUD and USD are
// the same currency.
const REGION_CURRENCY_SYMBOLS: Record<string, string> = {
  Afghanistan: "؋",
  Albania: "Lek",
  Algeria: "DA",
  Andorra: "€",
  Angola: "Kz",
  Argentina: "$",
  Armenia: "֏",
  Australia: "$",
  Austria: "€",
  Azerbaijan: "₼",
  Bahamas: "$",
  Bahrain: "BD",
  Bangladesh: "৳",
  Barbados: "$",
  Belarus: "Br",
  Belgium: "€",
  Belize: "$",
  Benin: "CFA",
  Bhutan: "Nu.",
  Bolivia: "Bs.",
  "Bosnia and Herzegovina": "KM",
  Botswana: "P",
  Brazil: "R$",
  Brunei: "$",
  Bulgaria: "лв",
  "Burkina Faso": "CFA",
  Burundi: "FBu",
  Cambodia: "៛",
  Cameroon: "FCFA",
  Canada: "$",
  "Cape Verde": "$",
  "Central African Republic": "FCFA",
  Chad: "FCFA",
  Chile: "$",
  China: "¥",
  Colombia: "$",
  Comoros: "CF",
  "Costa Rica": "₡",
  Croatia: "€",
  Cuba: "$",
  Cyprus: "€",
  "Czech Republic": "Kč",
  "Democratic Republic of the Congo": "FC",
  Denmark: "kr",
  Djibouti: "Fdj",
  Dominica: "EC$",
  "Dominican Republic": "RD$",
  Ecuador: "$",
  Egypt: "E£",
  "El Salvador": "$",
  "Equatorial Guinea": "FCFA",
  Eritrea: "Nfk",
  Estonia: "€",
  Eswatini: "L",
  Ethiopia: "Br",
  Fiji: "$",
  Finland: "€",
  France: "€",
  Gabon: "FCFA",
  Gambia: "D",
  Georgia: "₾",
  Germany: "€",
  Ghana: "₵",
  Greece: "€",
  Grenada: "EC$",
  Guatemala: "Q",
  Guinea: "FG",
  "Guinea-Bissau": "CFA",
  Guyana: "$",
  Haiti: "G",
  Honduras: "L",
  Hungary: "Ft",
  Iceland: "kr",
  India: "₹",
  Indonesia: "Rp",
  Iran: "﷼",
  Iraq: "ID",
  Ireland: "€",
  Israel: "₪",
  Italy: "€",
  "Ivory Coast": "CFA",
  Jamaica: "$",
  Japan: "¥",
  Jordan: "JD",
  Kazakhstan: "₸",
  Kenya: "KSh",
  Kiribati: "$",
  Kosovo: "€",
  Kuwait: "KD",
  Kyrgyzstan: "с",
  Laos: "₭",
  Latvia: "€",
  Lebanon: "LL",
  Lesotho: "L",
  Liberia: "L$",
  Libya: "LD",
  Liechtenstein: "CHF",
  Lithuania: "€",
  Luxembourg: "€",
  Madagascar: "Ar",
  Malawi: "MK",
  Malaysia: "RM",
  Maldives: "Rf",
  Mali: "CFA",
  Malta: "€",
  "Marshall Islands": "$",
  Mauritania: "UM",
  Mauritius: "₨",
  Mexico: "$",
  Micronesia: "$",
  Moldova: "L",
  Monaco: "€",
  Mongolia: "₮",
  Montenegro: "€",
  Morocco: "DH",
  Mozambique: "MT",
  Myanmar: "K",
  Namibia: "N$",
  Nauru: "$",
  Nepal: "₨",
  Netherlands: "€",
  "New Zealand": "$",
  Nicaragua: "C$",
  Niger: "CFA",
  Nigeria: "₦",
  "North Korea": "₩",
  "North Macedonia": "ден",
  Norway: "kr",
  Oman: "OR",
  Pakistan: "₨",
  Palau: "$",
  Palestine: "₪",
  Panama: "$",
  "Papua New Guinea": "K",
  Paraguay: "₲",
  Peru: "S/",
  Philippines: "₱",
  Poland: "zł",
  Portugal: "€",
  Qatar: "QR",
  "Republic of the Congo": "FCFA",
  Romania: "lei",
  Russia: "₽",
  Rwanda: "FRw",
  "Saint Kitts and Nevis": "EC$",
  "Saint Lucia": "EC$",
  "Saint Vincent and the Grenadines": "EC$",
  Samoa: "WS$",
  "San Marino": "€",
  "Sao Tome and Principe": "Db",
  "Saudi Arabia": "SR",
  Senegal: "CFA",
  Serbia: "дин",
  Seychelles: "₨",
  "Sierra Leone": "Le",
  Singapore: "$",
  Slovakia: "€",
  Slovenia: "€",
  "Solomon Islands": "$",
  Somalia: "Sh",
  "South Africa": "R",
  "South Korea": "₩",
  "South Sudan": "SSP",
  Spain: "€",
  "Sri Lanka": "Rs",
  Sudan: "SDG",
  Suriname: "$",
  Sweden: "kr",
  Switzerland: "CHF",
  Syria: "LS",
  Taiwan: "NT$",
  Tajikistan: "SM",
  Tanzania: "TSh",
  Thailand: "฿",
  "Timor-Leste": "$",
  Togo: "CFA",
  Tonga: "T$",
  "Trinidad and Tobago": "$",
  Tunisia: "DT",
  Turkey: "₺",
  Turkmenistan: "m",
  Tuvalu: "$",
  Uganda: "USh",
  Ukraine: "₴",
  "United Arab Emirates": "AED",
  "United Kingdom": "£",
  "United States": "$",
  Uruguay: "$U",
  Uzbekistan: "сўм",
  Vanuatu: "VT",
  "Vatican City": "€",
  Venezuela: "Bs.",
  Vietnam: "₫",
  Yemen: "YR",
  Zambia: "ZK",
  Zimbabwe: "Z$",
};

const DEFAULT_CURRENCY_SYMBOL = "$";

/** The currency symbol for a signed-in user's region, falling back to "$" when there's no region
    set (e.g. signed out, or an account created before this field existed) or it's unrecognized. */
export function getCurrencySymbolForRegion(region: string | null | undefined): string {
  if (!region) return DEFAULT_CURRENCY_SYMBOL;

  return REGION_CURRENCY_SYMBOLS[region] ?? DEFAULT_CURRENCY_SYMBOL;
}
